# Generated by Django 4.2.6 on 2023-10-21 23:14

import ai.classification.exceptions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassifiedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/",
                        validators=[ai.classification.exceptions.validate_image_size],
                        verbose_name="分類画像",
                    ),
                ),
                ("result", models.CharField(blank=True, default="", max_length=50)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
